# -*- coding: utf-8 -*-
"""
/***************************************************************************
 hsrrProcessor
                                 A QGIS plugin
 Plugin for processing HSRR data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-15
        copyright            : (C) 2020 by Drew
        email                : drew.bennett@ptsinternational.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""



import sys
sys.path.append('.')


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load hsrrProcessor class from file hsrrProcessor.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .hsrr_processor import hsrrProcessor
    return hsrrProcessor(iface)
